baseURL = "http://resume.sirot.org/"
languageCode = "en-us"
title = "My Resume"
theme = "hugo-orbit-theme"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Jean-Christophe Sirot Resume"
    author = "Jean-Christophe Sirot"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles.css"
    
    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: jc@sirot.org"
        title = "jc@sirot.org"
