baseURL = "https://cv.sirot.org/"
languageCode = "en-us"
title = "Jean-Christophe Sirot Resume"
theme = "hugo-orbit-jc-theme"
googleAnalytics = "UA-161581817-1"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Global Site
    title = "Jean-Christophe Sirot Resume"

# Meta
    description = "Jean-Christophe Sirot Resume"
    author = "Jean-Christophe Sirot"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles-3.css"
    
    # Profile section
    [params.profile]
        name = "Jean-Christophe Sirot"
        tagline = "Senior Software Engineer"
        avatar = "profile.jpg"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: jc@sirot.org"
        title = "jc@sirot.org"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/jcsirot"
        title = "linkedin.com/in/jcsirot"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/jcsirot"
        title = "github.com/jcsirot"

        [[params.contact.list]]
        class = "twitter"
        icon = "fa-twitter"
        url = "//twitter.com/jcsirot"
        title = "@jcsirot"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "MSc in Computer Science"
        college = "Telecom Nancy, Nancy, France"
        dates = "1999 — 2002"

        [[params.education.list]]
        degree = "MSc in Electronic Commerce — Technical"
        college = "Dublin City University, Dublin, Ireland"
        dates = "2001 — 2002"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "French"
        level = "Native"

        [[params.language.list]]
        language = "English"
        level = "Full professional proficiency"

        [[params.language.list]]
        language = "German"
        level = "Limited working proficiency"

        [[params.language.list]]
        language = "Japanese"
        level = "Elementary proficiency"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Learning Japanese at [INALCO](https://www.inalco.fr/)"

        [[params.interests.list]]
        interest = "Playing Video games and board games"


# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Who I am"
        summary = "I am a senior software development engineer with 20 years of experience in various domains, mainly digital signature, Public Key Infrastructure and Cloud Native. I love designing softwares, sharing knowledge and best practices with development teams to help them build better products."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"
        
        [[params.jobs.list]]
        position = "Staff Engineer"
        dates = "Dec 2021 — Present"
        company = "Aircall, Paris"
        details = '''Developer Productivity team
- Develop and promote internal tools along with best practices for the backend teams (AWS / Serverless micro-services / typescript)
- Collaborate with the architecture team to define the backend reference architecture'''

        [[params.jobs.list]]
        position = "Lead Software Engineer"
        dates = "May 2020 — Dec 2021"
        company = "Aircall, Paris"
        details = '''Led the Authentication team of 7 people. The team was responsible for:
- Extracting the authentication module from a Rails monolith, developing and deploying the new authentication stack
- Ensuring seamless migration of the customer authentication database'''

        [[params.jobs.list]]
        position = "Software Engineer"
        dates = "Oct 2017 — Jan 2020"
        company = "Docker Inc, Paris"
        details = '''
- Development of a platform to automatically run E2E tests of Kubernetes in order to verify the integration with Docker Entreprise.
- Work on the certification of Docker Entreprise as a CNCF Certified Kubernetes platform.
- Docker Compose maintainer / support engineer
- Docker App developer, worked on the CNAB specification conformance for Docker App'''

        [[params.jobs.list]]
        position = "Lead Developer / Java Expert"
        dates = "Feb 2016 — Sep 2017"
        company = "Weborama, Paris"
        details = '''As the lead developer of the BigSea team, I was responsible for the migration of the proof of concept product from Apache Storm to a production-ready Kubernetes-based application that creates sociological, demographic, and behavioral profiles.
- Developed and implemented new features using Java, Hadoop, and Spark
- Successfully migrated the application to a Kubernetes cluster running on AWS EC2 instances'''

        [[params.jobs.list]]
        position = "Quality Assurance Manager"
        dates = "Nov 2014 — Feb 2016"
        company = "Arkena, Ivry-sur-Seine"
        details = "Manager of the Arkena QA team: 6 engineers in Paris and Stockholm"

        [[params.jobs.list]]
        position = "CDN Quality Assurance Engineer"
        dates = "Dec 2013 — Nov 2014"
        company = "Arkena, Ivry-sur-Seine"
        details = "Design and setup the new Arkena CDN validation platform. Automation of the CDN components validation process"

        [[params.jobs.list]]
        position = "Build & Quality Assurance Manager"
        dates = "Apr 2011 — Nov 2013"
        company = "Cryptolog, Paris"
        details = "Lead of the quality assurance team. Management of the build environments (Windows, Linux, OSX) and tools for the dev teams. Development of the software quality guides and quality metrics analysis."

        [[params.jobs.list]]
        position = "Lead Developer"
        dates = "Jan 2005 — Apr 2011"
        company = "Cryptolog, Paris"
        details = "Technical lead of digital signature product suite. Manager of a development team of 4 people"

        [[params.jobs.list]]
        position = "Security Software Engineer"
        dates = "Oct 2002 — Jan 2005"
        company = "Cryptolog, Paris"
        details = "Development of libraries and servers applications in the digital signature and Public Key Infrastructure fields. Most develoment was made with Java and C."

    # Extra activities section
    [params.activities]
        enable = true
        icon = "fa-handshake-o"
        #icon = "fa-briefcase"
        title = "Extra activities"

        [[params.activities.list]]
        position = "Co-founder"
        dates = "May 2022-Present"
        company = "Kubernetes Community Days France"
        details = "Creation of Kubernetes Community Days France 2023, a conference focused on Cloud-Native and DevOps, sponsored by the Cloud Native Computing Foundation, which took place in Paris on March 7th, 2023."

        [[params.activities.list]]
        position = "Co-founder"
        dates = "May 2016 — Today"
        company = "Association Cloud Native Paris (CNCF Paris), Paris"
        details = "Creation of a non-profit organisation to promote Cloud Native concepts, technologies and the [Cloud Native Computing Foundation](https://cncf.io). We organize one meetup per month on [meetup.com](https://meetup.com/fr-FR/Cloud-Native-Computing-Paris/)."

        [[params.activities.list]]
        position = "Crew member"
        dates = "Nov 2015 — Today"
        company = "Paris Java User Group"
        details = "Member of the team organizing the [Paris JUG](https://https://www.parisjug.org/) monthly meetup. Since 2016 I am responsible of the *Young Blood*, the Paris JUG January event where some unexperienced speakers are coached and invited to do a 15 minute talk in front of the JUG public."

    # Talks section
    [params.talks]
        enable = true
        icon = "fa-comments"
        title = "Speaker experience"

        [[params.talks.list]]
        title = "Conference: La Cryptanalyse d'Enigma : entre espionnage et mathématiques"
        url = "https://youtu.be/TnxPRKPpEoA"
        date = "Apr 2022"
        conference = "Devoxx France 2022, Paris, France"
        details = "Une histoire de la machine de chiffrement Enigma et des attaques contre elle effectuées en Pologne et en Grande-Bretagne pendant la seconde guerre mondiale (Slides](https://bit.ly/3CjArC2)"

        [[params.talks.list]]
        title = "Developing New Applications with Docker App Package (workshop)"
        url = "https://www.openslava.sk/2019/#/workshops/04cbc435-e2bb-452a-9871-93d405282e9b"
        date = "Oct 2019"
        conference = "OpenSlava 19, Bratislava, Slovakia"
        details = "Workshop details: [https://github.com/jcsirot/docker-app-workshop-dc19](https://github.com/jcsirot/docker-app-workshop-dc19)"

        [[params.talks.list]]
        title = "Cycle de vie des applications dans Kubernetes"
        url = "https://youtu.be/-PrLE3FD6mw"
        date = "Apr 2019"
        conference = "Devoxx France 2019, Paris, France"

        [[params.talks.list]]
        title = "Java dans Docker Bonnes pratiques (fr)"
        url = "https://fr.slideshare.net/kanedafromparis/java-indocker-devoxxfr-2018"
        date = "Apr 2018"
        conference = "Devoxx France 2018, Paris, France and Devoxx Maroc, Marrakech, Nov 2018"
        details = "Video [https://youtu.be/vzpU2jxrxJ8](https://youtu.be/vzpU2jxrxJ8)"

        [[params.talks.list]]
        title = "Raconte-moi X.509 : anatomie d'une autorité de certification (fr)"
        url = "https://fr.slideshare.net/JeanChristopheSirot/racontemoi-x509-anatomie-dune-autorit-de-certification"
        date = "Apr 2017"
        conference = "Devoxx France 2017, Paris, France"
        details = "Video [https://youtu.be/DK2mEx5g-2g](https://youtu.be/DK2mEx5g-2g)"

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"

        [[params.projects.list]]
        title = "Simple Furigana"
        url = "https://ankiweb.net/shared/info/1444055400"
        tagline = "An [Anki 2.1](https://apps.ankiweb.net/) add-on providing support for adding or removing furigana on Japanese content in cards."

        [[params.projects.list]]
        title = "go-polly-tts"
        url = "https://github.com/jcsirot/go-polly-tts"
        tagline = "A simple command line interface TTS generator using [Amazon Polly](https://aws.amazon.com/fr/polly/) webservice."

        [[params.projects.list]]
        title = "digest.js"
        url = "https://github.com/jcsirot/digest.js"
        tagline = "A toy library implementing digests, HMAC and PBKDF algorithms in javascript."
        
        [[params.projects.list]]
        title = "Jenkins ansible plugin"
        url = "https://github.com/jenkinsci/ansible-plugin"
        tagline = "A jenkins plugin to run [ansible](https://www.ansible.com/) ad-hoc commands and playbooks."
